import type { Metadata } from 'next';
import { Red_Hat_Display } from 'next/font/google';

import '@/styles/globals.css';

const redHat = Red_Hat_Display({
  subsets: ['latin'], 
  weight: ['300','400','500','600','700','800','900'],
  variable: '--font-redhat',
});
export const metadata: Metadata = {
  title: 'MatinHomes',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={redHat.className}>
      <body className=' bg-[#EBEBEB]'>{children}</body>
    </html>
  );
}
